# Generated by Django 5.2.2 on 2025-06-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='available_products',
        ),
    ]
